# pubspec.yaml
name: gemma3n
description: A Flutter project leveraging on-device AI capabilities.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  permission_handler: ^12.0.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  crypto: ^3.0.5
  image_picker: ^1.0.8
  lottie: ^3.1.2